-- MySQL Script generated by MySQL Workbench
-- 12/22/14 21:37:28
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lunch_lady_land
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lunch_lady_land` ;
CREATE SCHEMA IF NOT EXISTS `lunch_lady_land` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `lunch_lady_land` ;

-- -----------------------------------------------------
-- Table `lunch_lady_land`.`office`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lunch_lady_land`.`office` ;

CREATE TABLE IF NOT EXISTS `lunch_lady_land`.`office` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phone` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lunch_lady_land`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lunch_lady_land`.`user` ;

CREATE TABLE IF NOT EXISTS `lunch_lady_land`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `office_id` INT NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_office1_idx` (`office_id` ASC),
  CONSTRAINT `fk_user_office1`
    FOREIGN KEY (`office_id`)
    REFERENCES `lunch_lady_land`.`office` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lunch_lady_land`.`resturant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lunch_lady_land`.`resturant` ;

CREATE TABLE IF NOT EXISTS `lunch_lady_land`.`resturant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(75) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `office_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_resturant_office1_idx` (`office_id` ASC),
  CONSTRAINT `fk_resturant_office1`
    FOREIGN KEY (`office_id`)
    REFERENCES `lunch_lady_land`.`office` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lunch_lady_land`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lunch_lady_land`.`order` ;

CREATE TABLE IF NOT EXISTS `lunch_lady_land`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `items_to_order` TEXT NOT NULL,
  `estimated_cost` DECIMAL(3,2) NOT NULL,
  `desired_time` TIME NOT NULL,
  `open` TINYINT(1) NOT NULL,
  `date` DATE NOT NULL,
  `resturant_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_resturant1_idx` (`resturant_id` ASC),
  INDEX `fk_order_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_order_resturant1`
    FOREIGN KEY (`resturant_id`)
    REFERENCES `lunch_lady_land`.`resturant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `lunch_lady_land`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

DELIMITER $$
DROP PROCEDURE IF EXISTS lunch_lady_land.updateResturant $$
CREATE PROCEDURE lunch_lady_land.updateResturant
(
	IN `inId` INT,
	IN `inName` VARCHAR(75),
	IN `inAddress` VARCHAR(100),
	IN `inPhone` VARCHAR(45),
	IN `inOffice_id` INT
)
BEGIN
IF EXISTS (SELECT id FROM resturant WHERE id = inId)
THEN
  UPDATE resturant SET name = inName, address = inAddress, phone = inPhone, office_id = inOffice_id WHERE id=inId;
END IF;
END $$
DELIMITER ;
